Map<String, dynamic> dataplans = {
  "MTN_PLAN": [
    {
      "id": 331,
      "dataplan_id": "331",
      "network": 1,
      "plan_type": "GIFTING",
      "plan_network": "MTN",
      "month_validate": "- 1 Day",
      "plan": "75.0MB",
      "plan_amount": "74",
    },
    {
      "id": 332,
      "dataplan_id": "332",
      "network": 1,
      "plan_type": "GIFTING",
      "plan_network": "MTN",
      "month_validate": "- 1 Day",
      "plan": "110.0MB",
      "plan_amount": "98",
    },
    {
      "id": 333,
      "dataplan_id": "333",
      "network": 1,
      "plan_type": "GIFTING",
      "plan_network": "MTN",
      "month_validate": "- 1 Day",
      "plan": "230.0MB",
      "plan_amount": "198",
    },
    {
      "id": 376,
      "dataplan_id": "376",
      "network": 1,
      "plan_type": "GIFTING",
      "plan_network": "MTN",
      "month_validate": "- 3 Days",
      "plan": "750.0MB",
      "plan_amount": "448",
    },
    {
      "id": 310,
      "dataplan_id": "310",
      "network": 1,
      "plan_type": "GIFTING",
      "plan_network": "MTN",
      "month_validate": "- 1 Day",
      "plan": "1.0GB",
      "plan_amount": "496",
    },
    {
      "id": 365,
      "dataplan_id": "365",
      "network": 1,
      "plan_type": "GIFTING",
      "plan_network": "MTN",
      "month_validate": "- 7 Days",
      "plan": "500.0MB",
      "plan_amount": "497",
    },
    {
      "id": 378,
      "dataplan_id": "378",
      "network": 1,
      "plan_type": "CORPORATE GIFTING",
      "plan_network": "MTN",
      "month_validate": "- 7 Days",
      "plan": "500.0MB",
      "plan_amount": "498",
    },
    {
      "id": 363,
      "dataplan_id": "363",
      "network": 1,
      "plan_type": "SME",
      "plan_network": "MTN",
      "month_validate": "- 7 Days",
      "plan": "500.0MB",
      "plan_amount": "498",
    },
    {
      "id": 370,
      "dataplan_id": "370",
      "network": 1,
      "plan_type": "GIFTING",
      "plan_network": "MTN",
      "month_validate": "- 2 Days",
      "plan": "1.5GB",
      "plan_amount": "597",
    },
    {
      "id": 404,
      "dataplan_id": "404",
      "network": 1,
      "plan_type": "CORPORATE GIFTING",
      "plan_network": "MTN",
      "month_validate": "- 7 Days",
      "plan": "1.0GB",
      "plan_amount": "645",
    },
    {
      "id": 312,
      "dataplan_id": "312",
      "network": 1,
      "plan_type": "GIFTING",
      "plan_network": "MTN",
      "month_validate": "- 7 Days",
      "plan": "1.2GB",
      "plan_amount": "745",
    },
    {
      "id": 314,
      "dataplan_id": "314",
      "network": 1,
      "plan_type": "GIFTING",
      "plan_network": "MTN",
      "month_validate": "- 2 Days",
      "plan": "2.0GB",
      "plan_amount": "747",
    },
    {
      "id": 356,
      "dataplan_id": "356",
      "network": 1,
      "plan_type": "SME",
      "plan_network": "MTN",
      "month_validate": "- 7 Days",
      "plan": "1.0GB",
      "plan_amount": "795",
    },
    {
      "id": 328,
      "dataplan_id": "328",
      "network": 1,
      "plan_type": "GIFTING",
      "plan_network": "MTN",
      "month_validate": "- 7 Days",
      "plan": "1.0GB",
      "plan_amount": "797",
    },
    {
      "id": 375,
      "dataplan_id": "375",
      "network": 1,
      "plan_type": "GIFTING",
      "plan_network": "MTN",
      "month_validate": "- 2 Days",
      "plan": "2.5GB",
      "plan_amount": "894",
    },
    {
      "id": 311,
      "dataplan_id": "311",
      "network": 1,
      "plan_type": "GIFTING",
      "plan_network": "MTN",
      "month_validate": "- 7 Days",
      "plan": "1.5GB",
      "plan_amount": "990",
    },
    {
      "id": 313,
      "dataplan_id": "313",
      "network": 1,
      "plan_type": "GIFTING",
      "plan_network": "MTN",
      "month_validate": "- 2 Days",
      "plan": "3.2GB",
      "plan_amount": "995",
    },
    {
      "id": 405,
      "dataplan_id": "405",
      "network": 1,
      "plan_type": "CORPORATE GIFTING",
      "plan_network": "MTN",
      "month_validate": "- 30 Days",
      "plan": "2.0GB",
      "plan_amount": "1290",
    },
    {
      "id": 360,
      "dataplan_id": "360",
      "network": 1,
      "plan_type": "GIFTING",
      "plan_network": "MTN",
      "month_validate": "- 30 Days",
      "plan": "2.0GB",
      "plan_amount": "1494",
    },
    {
      "id": 359,
      "dataplan_id": "359",
      "network": 1,
      "plan_type": "SME",
      "plan_network": "MTN",
      "month_validate": "- 30 Days",
      "plan": "2.0GB",
      "plan_amount": "1496",
    },
    {
      "id": 402,
      "dataplan_id": "402",
      "network": 1,
      "plan_type": "CORPORATE GIFTING",
      "plan_network": "MTN",
      "month_validate": "- 30 Days",
      "plan": "3.0GB",
      "plan_amount": "1935",
    },
    {
      "id": 327,
      "dataplan_id": "327",
      "network": 1,
      "plan_type": "GIFTING",
      "plan_network": "MTN",
      "month_validate": "- 30 Days",
      "plan": "2.7GB",
      "plan_amount": "1990",
    },
    {
      "id": 315,
      "dataplan_id": "315",
      "network": 1,
      "plan_type": "GIFTING",
      "plan_network": "MTN",
      "month_validate": "- 7 Days",
      "plan": "6.0GB",
      "plan_amount": "2485",
    },
    {
      "id": 373,
      "dataplan_id": "373",
      "network": 1,
      "plan_type": "GIFTING",
      "plan_network": "MTN",
      "month_validate": "- 30 Days",
      "plan": "3.5GB",
      "plan_amount": "2490",
    },
    {
      "id": 374,
      "dataplan_id": "374",
      "network": 1,
      "plan_type": "SME",
      "plan_network": "MTN",
      "month_validate": "- 30 Days",
      "plan": "3.5GB",
      "plan_amount": "2495",
    },
    {
      "id": 357,
      "dataplan_id": "357",
      "network": 1,
      "plan_type": "SME",
      "plan_network": "MTN",
      "month_validate": "- 7 Days",
      "plan": "6.0GB",
      "plan_amount": "2498",
    },
    {
      "id": 403,
      "dataplan_id": "403",
      "network": 1,
      "plan_type": "CORPORATE GIFTING",
      "plan_network": "MTN",
      "month_validate": "- 30 Days",
      "plan": "5.0GB",
      "plan_amount": "3225",
    },
    {
      "id": 381,
      "dataplan_id": "381",
      "network": 1,
      "plan_type": "CORPORATE GIFTING",
      "plan_network": "MTN",
      "month_validate": "- 7 Days",
      "plan": "11.0GB",
      "plan_amount": "3490",
    },
    {
      "id": 329,
      "dataplan_id": "329",
      "network": 1,
      "plan_type": "GIFTING",
      "plan_network": "MTN",
      "month_validate": "- 30 Days",
      "plan": "10.0GB",
      "plan_amount": "4485",
    },
    {
      "id": 362,
      "dataplan_id": "362",
      "network": 1,
      "plan_type": "SME",
      "plan_network": "MTN",
      "month_validate": "- 30 Days",
      "plan": "10.0GB",
      "plan_amount": "4495",
    },
    {
      "id": 440,
      "dataplan_id": "440",
      "network": 1,
      "plan_type": "CORPORATE GIFTING",
      "plan_network": "MTN",
      "month_validate": "- 30 Days",
      "plan": "10.0GB",
      "plan_amount": "4545",
    },
    {
      "id": 322,
      "dataplan_id": "322",
      "network": 1,
      "plan_type": "GIFTING",
      "plan_network": "MTN",
      "month_validate": "- 30 Days",
      "plan": "12.5GB",
      "plan_amount": "5490",
    },
    {
      "id": 358,
      "dataplan_id": "358",
      "network": 1,
      "plan_type": "SME",
      "plan_network": "MTN",
      "month_validate": "- 30 Days",
      "plan": "12.5GB",
      "plan_amount": "5500",
    },
    {
      "id": 336,
      "dataplan_id": "336",
      "network": 1,
      "plan_type": "GIFTING",
      "plan_network": "MTN",
      "month_validate": "- 30 Days",
      "plan": "16.5GB",
      "plan_amount": "6400",
    },
    {
      "id": 368,
      "dataplan_id": "368",
      "network": 1,
      "plan_type": "GIFTING",
      "plan_network": "MTN",
      "month_validate": "- 30 Days",
      "plan": "20.0GB",
      "plan_amount": "7490",
    },
    {
      "id": 369,
      "dataplan_id": "369",
      "network": 1,
      "plan_type": "GIFTING",
      "plan_network": "MTN",
      "month_validate": "- 30 Days",
      "plan": "25.0GB",
      "plan_amount": "8985",
    },
    {
      "id": 330,
      "dataplan_id": "330",
      "network": 1,
      "plan_type": "GIFTING",
      "plan_network": "MTN",
      "month_validate": "- 30 Days",
      "plan": "36.0GB",
      "plan_amount": "10890",
    },
    {
      "id": 361,
      "dataplan_id": "361",
      "network": 1,
      "plan_type": "GIFTING",
      "plan_network": "MTN",
      "month_validate": "- 30 Days",
      "plan": "75.0GB",
      "plan_amount": "17920",
    },
    {
      "id": 364,
      "dataplan_id": "364",
      "network": 1,
      "plan_type": "GIFTING",
      "plan_network": "MTN",
      "month_validate": "- 30 Days",
      "plan": "165.0GB",
      "plan_amount": "34800",
    },
    {
      "id": 340,
      "dataplan_id": "340",
      "network": 1,
      "plan_type": "GIFTING",
      "plan_network": "MTN",
      "month_validate": "- 60 Days",
      "plan": "150.0GB",
      "plan_amount": "39400",
    },
    {
      "id": 341,
      "dataplan_id": "341",
      "network": 1,
      "plan_type": "GIFTING",
      "plan_network": "MTN",
      "month_validate": "- 60 Days",
      "plan": "200.0GB",
      "plan_amount": "49250",
    },
  ],
  "GLO_PLAN": [
    {
      "id": 282,
      "dataplan_id": "282",
      "network": 2,
      "plan_type": "CORPORATE GIFTING",
      "plan_network": "GLO",
      "month_validate": "- 14 Days",
      "plan": "200.0MB",
      "plan_amount": "96",
    },
    {
      "id": 317,
      "dataplan_id": "317",
      "network": 2,
      "plan_type": "SME",
      "plan_network": "GLO",
      "month_validate": "- 1 Day",
      "plan": "750.0MB",
      "plan_amount": "210",
    },
    {
      "id": 283,
      "dataplan_id": "283",
      "network": 2,
      "plan_type": "CORPORATE GIFTING",
      "plan_network": "GLO",
      "month_validate": "- 1 Month",
      "plan": "500.0MB",
      "plan_amount": "220",
    },
    {
      "id": 428,
      "dataplan_id": "428",
      "network": 2,
      "plan_type": "GIFTING",
      "plan_network": "GLO",
      "month_validate": "- 3 Days",
      "plan": "1.0GB",
      "plan_amount": "290",
    },
    {
      "id": 318,
      "dataplan_id": "318",
      "network": 2,
      "plan_type": "SME",
      "plan_network": "GLO",
      "month_validate": "- 1 Day",
      "plan": "1.5GB",
      "plan_amount": "310",
    },
    {
      "id": 431,
      "dataplan_id": "431",
      "network": 2,
      "plan_type": "GIFTING",
      "plan_network": "GLO",
      "month_validate": "- 7 Days",
      "plan": "1.0GB",
      "plan_amount": "335",
    },
    {
      "id": 284,
      "dataplan_id": "284",
      "network": 2,
      "plan_type": "CORPORATE GIFTING",
      "plan_network": "GLO",
      "month_validate": "- 1 Month",
      "plan": "1.0GB",
      "plan_amount": "440",
    },
    {
      "id": 319,
      "dataplan_id": "319",
      "network": 2,
      "plan_type": "SME",
      "plan_network": "GLO",
      "month_validate": "- 2 Days",
      "plan": "2.5GB",
      "plan_amount": "510",
    },
    {
      "id": 429,
      "dataplan_id": "429",
      "network": 2,
      "plan_type": "GIFTING",
      "plan_network": "GLO",
      "month_validate": "- 3 Days",
      "plan": "3.0GB",
      "plan_amount": "870",
    },
    {
      "id": 285,
      "dataplan_id": "285",
      "network": 2,
      "plan_type": "CORPORATE GIFTING",
      "plan_network": "GLO",
      "month_validate": "- 1 Month",
      "plan": "2.0GB",
      "plan_amount": "880",
    },
    {
      "id": 432,
      "dataplan_id": "432",
      "network": 2,
      "plan_type": "GIFTING",
      "plan_network": "GLO",
      "month_validate": "- 7 Days",
      "plan": "3.0GB",
      "plan_amount": "1005",
    },
    {
      "id": 286,
      "dataplan_id": "286",
      "network": 2,
      "plan_type": "CORPORATE GIFTING",
      "plan_network": "GLO",
      "month_validate": "- 1 Month",
      "plan": "3.0GB",
      "plan_amount": "1320",
    },
    {
      "id": 430,
      "dataplan_id": "430",
      "network": 2,
      "plan_type": "GIFTING",
      "plan_network": "GLO",
      "month_validate": "- 3 Days",
      "plan": "5.0GB",
      "plan_amount": "1450",
    },
    {
      "id": 433,
      "dataplan_id": "433",
      "network": 2,
      "plan_type": "GIFTING",
      "plan_network": "GLO",
      "month_validate": "- 7 Days",
      "plan": "5.0GB",
      "plan_amount": "1675",
    },
    {
      "id": 320,
      "dataplan_id": "320",
      "network": 2,
      "plan_type": "SME",
      "plan_network": "GLO",
      "month_validate": "- 7 Days",
      "plan": "10.0GB",
      "plan_amount": "1995",
    },
    {
      "id": 287,
      "dataplan_id": "287",
      "network": 2,
      "plan_type": "CORPORATE GIFTING",
      "plan_network": "GLO",
      "month_validate": "- 1 Month",
      "plan": "5.0GB",
      "plan_amount": "2200",
    },
    {
      "id": 288,
      "dataplan_id": "288",
      "network": 2,
      "plan_type": "CORPORATE GIFTING",
      "plan_network": "GLO",
      "month_validate": "- 1 Month",
      "plan": "10.0GB",
      "plan_amount": "4400",
    },
  ],
  "AIRTEL_PLAN": [
    {
      "id": 342,
      "dataplan_id": "342",
      "network": 4,
      "plan_type": "GIFTING",
      "plan_network": "AIRTEL",
      "month_validate": "- 1 Day",
      "plan": "75.0MB",
      "plan_amount": "75",
    },
    {
      "id": 343,
      "dataplan_id": "343",
      "network": 4,
      "plan_type": "GIFTING",
      "plan_network": "AIRTEL",
      "month_validate": "- 1 Day",
      "plan": "100.0MB",
      "plan_amount": "99",
    },
    {
      "id": 344,
      "dataplan_id": "344",
      "network": 4,
      "plan_type": "CORPORATE GIFTING",
      "plan_network": "AIRTEL",
      "month_validate": "- 2 Days",
      "plan": "200.0MB",
      "plan_amount": "199",
    },
    {
      "id": 390,
      "dataplan_id": "390",
      "network": 4,
      "plan_type": "GIFTING",
      "plan_network": "AIRTEL",
      "month_validate": "- 2 Days",
      "plan": "200.0MB",
      "plan_amount": "199",
    },
    {
      "id": 345,
      "dataplan_id": "345",
      "network": 4,
      "plan_type": "GIFTING",
      "plan_network": "AIRTEL",
      "month_validate": "- 1 Day",
      "plan": "300.0MB",
      "plan_amount": "299",
    },
    {
      "id": 347,
      "dataplan_id": "347",
      "network": 4,
      "plan_type": "SME",
      "plan_network": "AIRTEL",
      "month_validate": "- 1 Day",
      "plan": "1.0GB",
      "plan_amount": "495",
    },
    {
      "id": 386,
      "dataplan_id": "386",
      "network": 4,
      "plan_type": "CORPORATE GIFTING",
      "plan_network": "AIRTEL",
      "month_validate": "- 7 Days",
      "plan": "500.0MB",
      "plan_amount": "497",
    },
    {
      "id": 387,
      "dataplan_id": "387",
      "network": 4,
      "plan_type": "GIFTING",
      "plan_network": "AIRTEL",
      "month_validate": "- 7 Days",
      "plan": "500.0MB",
      "plan_amount": "498",
    },
    {
      "id": 309,
      "dataplan_id": "309",
      "network": 4,
      "plan_type": "SME",
      "plan_network": "AIRTEL",
      "month_validate": "- 2 Days",
      "plan": "1.5GB",
      "plan_amount": "622",
    },
    {
      "id": 397,
      "dataplan_id": "397",
      "network": 4,
      "plan_type": "SME",
      "plan_network": "AIRTEL",
      "month_validate": "- 2 Days",
      "plan": "2.0GB",
      "plan_amount": "748",
    },
    {
      "id": 388,
      "dataplan_id": "388",
      "network": 4,
      "plan_type": "CORPORATE GIFTING",
      "plan_network": "AIRTEL",
      "month_validate": "- 7 Days",
      "plan": "1.0GB",
      "plan_amount": "796",
    },
    {
      "id": 348,
      "dataplan_id": "348",
      "network": 4,
      "plan_type": "GIFTING",
      "plan_network": "AIRTEL",
      "month_validate": "- 7 Days",
      "plan": "1.0GB",
      "plan_amount": "798",
    },
    {
      "id": 351,
      "dataplan_id": "351",
      "network": 4,
      "plan_type": "SME",
      "plan_network": "AIRTEL",
      "month_validate": "- 2 Days",
      "plan": "3.0GB",
      "plan_amount": "995",
    },
    {
      "id": 349,
      "dataplan_id": "349",
      "network": 4,
      "plan_type": "GIFTING",
      "plan_network": "AIRTEL",
      "month_validate": "- 7 Days",
      "plan": "1.5GB",
      "plan_amount": "997",
    },
    {
      "id": 350,
      "dataplan_id": "350",
      "network": 4,
      "plan_type": "CORPORATE GIFTING",
      "plan_network": "AIRTEL",
      "month_validate": "- 30 Days",
      "plan": "2.0GB",
      "plan_amount": "1490",
    },
    {
      "id": 355,
      "dataplan_id": "355",
      "network": 4,
      "plan_type": "SME",
      "plan_network": "AIRTEL",
      "month_validate": "- 2 Days",
      "plan": "5.0GB",
      "plan_amount": "1495",
    },
    {
      "id": 389,
      "dataplan_id": "389",
      "network": 4,
      "plan_type": "GIFTING",
      "plan_network": "AIRTEL",
      "month_validate": "- 30 Days",
      "plan": "2.0GB",
      "plan_amount": "1495",
    },
    {
      "id": 392,
      "dataplan_id": "392",
      "network": 4,
      "plan_type": "GIFTING",
      "plan_network": "AIRTEL",
      "month_validate": "- 7 Days",
      "plan": "3.0GB",
      "plan_amount": "1496",
    },
    {
      "id": 353,
      "dataplan_id": "353",
      "network": 4,
      "plan_type": "CORPORATE GIFTING",
      "plan_network": "AIRTEL",
      "month_validate": "- 30 Days",
      "plan": "3.0GB",
      "plan_amount": "1994",
    },
    {
      "id": 391,
      "dataplan_id": "391",
      "network": 4,
      "plan_type": "GIFTING",
      "plan_network": "AIRTEL",
      "month_validate": "- 30 Days",
      "plan": "3.0GB",
      "plan_amount": "1998",
    },
    {
      "id": 399,
      "dataplan_id": "399",
      "network": 4,
      "plan_type": "GIFTING",
      "plan_network": "AIRTEL",
      "month_validate": "- 30 Days",
      "plan": "4.0GB",
      "plan_amount": "2494",
    },
    {
      "id": 354,
      "dataplan_id": "354",
      "network": 4,
      "plan_type": "CORPORATE GIFTING",
      "plan_network": "AIRTEL",
      "month_validate": "- 30 Days",
      "plan": "4.0GB",
      "plan_amount": "2495",
    },
    {
      "id": 395,
      "dataplan_id": "395",
      "network": 4,
      "plan_type": "CORPORATE GIFTING",
      "plan_network": "AIRTEL",
      "month_validate": "- 30 Days",
      "plan": "6.0GB",
      "plan_amount": "2992",
    },
    {
      "id": 421,
      "dataplan_id": "421",
      "network": 4,
      "plan_type": "GIFTING",
      "plan_network": "AIRTEL",
      "month_validate": "- 7 Days",
      "plan": "8.5GB",
      "plan_amount": "2997",
    },
    {
      "id": 385,
      "dataplan_id": "385",
      "network": 4,
      "plan_type": "CORPORATE GIFTING",
      "plan_network": "AIRTEL",
      "month_validate": "- 30 Days",
      "plan": "10.0GB",
      "plan_amount": "3985",
    },
    {
      "id": 396,
      "dataplan_id": "396",
      "network": 4,
      "plan_type": "CORPORATE GIFTING",
      "plan_network": "AIRTEL",
      "month_validate": "- 30 Days",
      "plan": "13.0GB",
      "plan_amount": "4990",
    },
  ],
  "9MOBILE_PLAN": [
    {
      "id": 398,
      "dataplan_id": "398",
      "network": 3,
      "plan_type": "SME",
      "plan_network": "9MOBILE",
      "month_validate": "- 30 Days",
      "plan": "500.0MB",
      "plan_amount": "150",
    },
    {
      "id": 235,
      "dataplan_id": "235",
      "network": 3,
      "plan_type": "CORPORATE GIFTING",
      "plan_network": "9MOBILE",
      "month_validate": "- 30 Days",
      "plan": "500.0MB",
      "plan_amount": "160",
    },
    {
      "id": 300,
      "dataplan_id": "300",
      "network": 3,
      "plan_type": "CORPORATE GIFTING",
      "plan_network": "9MOBILE",
      "month_validate": "- 30 Days",
      "plan": "1.0GB",
      "plan_amount": "320",
    },
    {
      "id": 228,
      "dataplan_id": "228",
      "network": 3,
      "plan_type": "CORPORATE GIFTING",
      "plan_network": "9MOBILE",
      "month_validate": "- 30 Days",
      "plan": "2.0GB",
      "plan_amount": "640",
    },
    {
      "id": 237,
      "dataplan_id": "237",
      "network": 3,
      "plan_type": "CORPORATE GIFTING",
      "plan_network": "9MOBILE",
      "month_validate": "- 30 Days",
      "plan": "3.0GB",
      "plan_amount": "960",
    },
    {
      "id": 316,
      "dataplan_id": "316",
      "network": 3,
      "plan_type": "CORPORATE GIFTING",
      "plan_network": "9MOBILE",
      "month_validate": "- 30 Days",
      "plan": "5.0GB",
      "plan_amount": "1600",
    },
    {
      "id": 239,
      "dataplan_id": "239",
      "network": 3,
      "plan_type": "CORPORATE GIFTING",
      "plan_network": "9MOBILE",
      "month_validate": "- 30 Days",
      "plan": "10.0GB",
      "plan_amount": "3200",
    },
  ],
};

Map<String, dynamic> cableplans = {
  "DStv": [
    { "plan_id": 6, "plan_name": "DStv Yanga", "price": 6000 },
    { "plan_id": 7, "plan_name": "DStv Compact", "price": 19000 },
    { "plan_id": 8, "plan_name": "DStv Compact Plus", "price": 30000 },
    { "plan_id": 9, "plan_name": "DStv Premium", "price": 44500 },
    { "plan_id": 19, "plan_name": "DStv Confam", "price": 11000 },
    { "plan_id": 20, "plan_name": "DStv PADI", "price": 4400 }
  ],
  "GOtv": [
    { "plan_id": 2, "plan_name": "GOtv Max", "price": 8500 },
    { "plan_id": 16, "plan_name": "GOtv Jinja", "price": 3900 },
    { "plan_id": 17, "plan_name": "GOtv Jolli", "price": 5800 },
    { "plan_id": 34, "plan_name": "GOtv LITE (Smallie) - Monthly", "price": 1900 },
    { "plan_id": 50, "plan_name": "GOtv Supa (Monthly)", "price": 11400 }
  ],
  "STARTIME": [
    { "plan_id": 10, "plan_name": "NOVA (1 Month)", "price": 1900 },
    { "plan_id": 37, "plan_name": "Nova - 600 Naira - 1 Week", "price": 600 },
    { "plan_id": 11, "plan_name": "CLASSIC (1 Month)", "price": 5500 },
    { "plan_id": 40, "plan_name": "Classic - 1900 Naira - 1 Week", "price": 1900 },
    { "plan_id": 12, "plan_name": "BASIC (1 Month)", "price": 3700 },
    { "plan_id": 38, "plan_name": "Basic - 1250 Naira - 1 Week", "price": 1250 },
    { "plan_id": 13, "plan_name": "SMART (1 Month)", "price": 4700 },
    { "plan_id": 39, "plan_name": "Smart - 1550 Naira - 1 Week", "price": 1550 },
    { "plan_id": 15, "plan_name": "SUPER (1 Month)", "price": 9000 },
    { "plan_id": 41, "plan_name": "Super - 3000 Naira - 1 Week", "price": 3000 }
  ]
};